services:
  app:
    build: .
    container_name: python_app
    depends_on:
      - db
    environment:
      - DB_HOST=localhost
      - DB_PORT=5432
      - DB_NAME=user_data
      - DB_USER=postgres
      - DB_PASSWORD=Pavlo0509
    tty: true
    volumes:
      - .:/app

  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Pavlo0509
      POSTGRES_DB: user_data
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
